### ISSUE TITLE
The srt parser rejects valid srt files

### ISSUE THREAD

**Issue by Franciman** [Franciman/electron-sheeps#12]
`subtitle`, the current library we're using to parse srt files, fails to parse some correct srt files.
Instead, we could use `subtitles-parser` which accepts more srt files.
The only downside is that `subtitle` has some very handy functions like toMS and toSrtTime which `subtitles-parser` lacks and we should implement them

**Comment by doppioandante** [comment]
I think those functions are trivial enough to re-implement.
Can you attach a relevant srt field that causes `subtitle` to fail? We may want to report this upstream in case it is an objective bug.

**Comment by frankplus** [comment]
It seems that the problem of the `subtitle` module arises during the parsing of 00:00:00,000
the traceback is the following

```
 /home/francesco/Desktop/electron-sheeps/node_modules/subtitle/lib/parseTimestamps.js:23 Uncaught TypeError: Cannot read property '1' of null
    at parseTimestamps (/home/francesco/Desktop/electron-sheeps/node_modules/subtitle/lib/parseTimestamps.js:23:22)
    at source.reduce (/home/francesco/Desktop/electron-sheeps/node_modules/subtitle/lib/parse.js:34:30)
    at Array.reduce (native)
    at Object.parse (/home/francesco/Desktop/electron-sheeps/node_modules/subtitle/lib/parse.js:23:17)
```

the error is thrown inside `parseTimestamps.js` of `subtitle`
```
module.exports = function parseTimestamps (value) {
  const match = RE.exec(value)
  return {
    start: toMS(match[1]),
    end: toMS(match[2])
  }
}

```
here the execution of the regex pattern `/^(\d{2}:\d{2}:\d{2},\d{3}) --> (\d{2}:\d{2}:\d{2},\d{3})$/` with the string `00:00:00,000 --> 00:00:08,999` returns a mismatch why?

**Comment by doppioandante** [comment]
A quick try inside firefox's console matches that specific pattern with the regex. No clue.
EDIT: it works with electron's console as well.

**Comment by doppioandante** [comment]
Should be fixed by https://github.com/gsantiago/subtitle.js/pull/17/ when it lands.
