### ISSUE TITLE
cannot make pex, libavformat package not found error

### ISSUE THREAD

**Issue by frankplus** [Franciman/electron-sheeps#5]
This error is shown while compiling on linux mint

> make[1]: Entering directory '/home/francesco/Desktop/electron-sheeps/extra/media_processor'
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
g++ -c -std=c++14  -O2 keyframe_extractor.cpp -o .keyframe_extractor.o
keyframe_extractor.cpp:7:34: fatal error: libavformat/avformat.h: No such file or directory
compilation terminated.
> 

This problem is due to the package ffmpeg which is removed from ubuntu repositories and replaced by libav instead.

**Comment by doppioandante** [comment]
Now fixed.
